---
- name: Backup Huawei Switch Configuration
  hosts: HUAWEI_SW
  gather_facts: no
  vars:
    backup_dir: "/root/network/backups/HUAWEI"
  tasks:
    - name: Ensure SSH port is set
      set_fact:
        ansible_port: "{{ ansible_port | default(9337) }}"

    - name: Backup configuration (with password authentication)
      when: ansible_ssh_pass is defined
      block:
        - name: Check if sshpass is installed
          shell: which sshpass
          register: sshpass_check
          delegate_to: localhost
          run_once: true

        - name: Fail if sshpass is not installed
          fail:
            msg: >-
              sshpass is required for password-based SSH authentication.
              Please install sshpass on the Semaphore host and rerun the playbook.
          when: sshpass_check.stdout == ""

        - name: Gather configuration using sshpass
          shell: >
            sshpass -p '{{ ansible_ssh_pass }}'
            ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
            {{ ansible_user }}@{{ inventory_hostname }}
            "display current-configuration"
          register: export
          delegate_to: localhost

        - name: Save configuration locally
          copy:
            content: "{{ export.stdout }}"
            dest: "{{ backup_dir }}/{{ inventory_hostname }}_config_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.cfg"
          delegate_to: localhost

    - name: Backup configuration (passwordless authentication)
      when: ansible_ssh_pass is not defined
      block:
        - name: Gather configuration without password
          shell: >
            ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
            {{ ansible_user }}@{{ inventory_hostname }}
            "display current-configuration"
          register: export
          delegate_to: localhost

        - name: Save configuration locally
          copy:
            content: "{{ export.stdout }}"
            dest: "{{ backup_dir }}/{{ inventory_hostname }}_config_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.cfg"
          delegate_to: localhost
