---
# Playbook to backup Huawei switch configurations

- name: Collect date and create backup directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Collect today's date
      set_fact:
        DTG: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    
    - name: Create backup directory
      file:
        path: "/root/network/backups/HUAWEI/bkp_{{ DTG }}/Switches/"
        state: directory

- name: Backup Huawei switch configuration
  hosts: HUAWEI
  gather_facts: false
  tasks:
    - name: Backup configuration file
      ce_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "/root/network/backups/HUAWEI/bkp_{{ hostvars['localhost']['DTG'] }}/Switches/"
