---
- name: Backup Huawei Switch Configuration
  hosts: HUAWEI_SW
  gather_facts: no
  vars:
    backup_dir: "/root/network/backups/HUAWEI"

  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Collect full configuration using raw command
      raw: |
        sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
        {{ ansible_user }}@{{ inventory_hostname }} "
        display current-configuration | no-more"
      register: config_output
      delegate_to: localhost

    - name: Save configuration to backup directory
      copy:
        content: "{{ config_output.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.cfg"
      delegate_to: localhost
