---
- name: Backup Mikrotik
  hosts: mikrotik
  gather_facts: false
  vars:
    backup_dir: "/root/network/backup"
  tasks:
    - name: Export Mikrotik configuration to file
      ansible.builtin.shell: >-
        sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ inventory_hostname }} '/export file={{ inventory_hostname }}_backup'
      register: export
      delegate_to: localhost

    - name: Download the backup file from the MikroTik device
      ansible.builtin.fetch:
        src: "/{{ inventory_hostname }}_backup.rsc"  # Adding the .rsc extension
        dest: "{{ backup_dir }}/"
        flat: yes
      when: export is defined
