---
- name: Backup Huawei Switch Configurations via SSH
  hosts: HUAWEI_SW
  gather_facts: no
  vars:
    backup_dir: "{{ hostvars[inventory_hostname]['backup_dir'] }}"
  tasks:
    - name: Ensure the backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Collect configuration via SSH
      huawei.vrp.vrp_command:
        commands:
          - display current-configuration
      register: config_output

    - name: Extract sysname from configuration
      set_fact:
        sysname: "{{ (config_output.stdout | regex_search('sysname\\s+(\\S+)')).group(1) | default('unknown_' + inventory_hostname) }}"

    - name: Save configuration to backup file
      copy:
        content: "{{ config_output.stdout | join('\n') }}"
        dest: "{{ backup_dir }}/{{ sysname }}_{{ ansible_date_time.iso8601_basic }}.txt"

    - name: Display success message
      debug:
        msg: "Backup successful for {{ sysname }}. Configuration saved to {{ backup_dir }}/{{ sysname }}_{{ ansible_date_time.iso8601_basic }}.txt"
