# Playbook to backup Huawei switch configurations

- name: Collect date and create backup directory
  hosts: HUAWEI
  gather_facts: false
  tasks:
    - name: Collect today's date
      set_fact:
        DTG: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    
    - name: Create backup directory
      file:
        path: "/root/network/backups/HUAWEI/bkp_{{ DTG }}/Switches/"
        state: directory

    - name: Set SSH port (set default to 22 if port is not defined)
      set_fact:
        ansible_port: "{{ ansible_port | default(22) }}"

    - name: Run backup with password (when password is defined)
      when: ansible_ssh_pass is defined
      block:
        - name: Ensure that sshpass is installed
          ansible.builtin.shell: "whereis sshpass | awk '{print $2}'"
          run_once: yes
          register: sshpass
          delegate_to: localhost

        - name: Fail if sshpass is not installed
          ansible.builtin.fail:
            msg: >-
              Playbook requires sshpass to use password authentication. Please install
              sshpass and re-run the same playbook.
              See https://www.redhat.com/sysadmin/ssh-automation-sshpass for details.
          when: sshpass.stdout|length == 0

- name: Backup Huawei switch configuration
  hosts: HUAWEI
  gather_facts: false
  tasks:
    - name: Backup configuration file
      ce_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "/root/network/backups/HUAWEI/bkp_{{ hostvars['localhost']['DTG'] }}/Switches/"
