---
- name: Backup Huawei Switch Configurations via SSH
  hosts: all
  gather_facts: no
  vars:
    backup_directory: "{{ backup_directory }}"
  tasks:
    - name: Ensure the backup directory exists
      ansible.builtin.file:
        path: "{{ backup_directory }}"
        state: directory
        mode: '0755'

    - name: Collect configuration via SSH
      ansible.builtin.command:
        cmd: "display current-configuration"
      register: config_output

    - name: Extract sysname from configuration
      set_fact:
        sysname: "{{ (config_output.stdout | regex_search('sysname\\s+(\\S+)')).group(1) | default('unknown_' + inventory_hostname) }}"

    - name: Save configuration to backup file
      copy:
        content: "{{ config_output.stdout }}"
        dest: "{{ backup_directory }}/{{ sysname }}_{{ ansible_date_time.iso8601_basic }}.txt"

    - name: Display success message
      debug:
        msg: "Backup successful for {{ sysname }}. Configuration saved to {{ backup_directory }}/{{ sysname }}_{{ ansible_date_time.iso8601_basic }}.txt"
