---
- name: Backup Cisco Nexus configs
  hosts: nxos
  gather_facts: no
  collections:
    - cisco.nxos
    - ansible.netcommon

  tasks:
    - name: Create backup directory per device (on controller)
      delegate_to: localhost
      run_once: false
      ansible.builtin.file:
        path: "/root/network/backups/CORE_SW/{{ inventory_hostname }}"
        state: directory
        mode: "0755"

    - name: Backup running configuration
      cisco.nxos.nxos_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}-{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}.cfg"
          dir_path: "/root/network/backups/CORE_SW/{{ inventory_hostname }}"
