---
# BACKUP HUAWEI SWITCHES - Optimized Playbook
# This playbook creates a directory for backups and saves Huawei switch configurations.

# Task to create a directory for backups
- name: Collect date and create backup directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Collect today's date
      set_fact:
        DTG: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Pass DTG to all hosts
      add_host:
        name: "{{ item }}"
        groups: HUAWEI_SW
        DTG: "{{ DTG }}"
      with_items: "{{ groups['HUAWEI_SW'] }}"

    - name: Create directory for backups
      file:
        path: "/root/network/backups/HUAWEI/bkp_{{ DTG }}/Switches/"
        state: directory
  run_once: true

    - name: Set ssh port (set defualt 22 port when port is not defined)
      set_fact:
        ansible_port: "{{ ansible_port | default(22) }}"

    - name: Run backup with password (when password is defined)
      when: ansible_ssh_pass is defined
      block:

      - name: Ensure that sshpass is installed
        ansible.builtin.shell: whereis sshpass | awk '{print $2}'
        run_once: yes
        register: sshpass
        delegate_to: localhost

      - ansible.builtin.fail:
          msg: >-
            Playbook requrie sshpass to use password authenication, please install
            sshpass and re-run same playbook again. 
            You can found details in https://www.redhat.com/sysadmin/ssh-automation-sshpass
        when: sshpass.stdout|length == 0

# Task to back up Huawei switch configurations
- name: Backup Huawei switch configuration
  hosts: HUAWEI_SW
  gather_facts: false
  tasks:
    - name: Ensure screen-length is set to 0
      ansible.netcommon.cli_command:
        command: |
          system-view
          screen-width 60
      register: cli_output

    - name: Copy the configuration file of each Huawei switch to a .cfg file
      ce_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "/root/network/backups/HUAWEI/bkp_{{ hostvars['localhost']['DTG'] }}/Switches/"

