---
- name: MikroTik full + script backup (Semaphore-safe via localhost SSH)
  hosts: NAT_RTR
  gather_facts: no

  vars:
    backup_base_dir: "/root/network/backups/NAT_RTR"  # local (Semaphore/controller)
    retention_keep: 10
    ssh_args_common: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  pre_tasks:
    - name: Ensure per-host backup directory exists (local)
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ backup_base_dir }}/{{ inventory_hostname }}"
        state: directory
        mode: "0750"

    - name: Set backup timestamp (local)
      delegate_to: localhost
      ansible.builtin.set_fact:
        backup_ts: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    - name: Ensure SSH port is defined (default 22)
      ansible.builtin.set_fact:
        ansible_port: "{{ ansible_port | default(22) }}"

    - name: Check if sshpass exists (local) when password is used
      when: ansible_ssh_pass is defined
      delegate_to: localhost
      register: sshpass_path
      changed_when: false
      failed_when: false
      ansible.builtin.command: command -v sshpass

    - name: Install sshpass (local) if missing
      when:
        - ansible_ssh_pass is defined
        - (sshpass_path.rc is defined) and (sshpass_path.rc != 0)
      delegate_to: localhost
      become: yes
      ansible.builtin.shell: |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update -y && apt-get install -y sshpass
        elif command -v yum >/dev/null 2>&1 || command -v dnf >/dev/null 2>&1; then
          (command -v yum && yum install -y epel-release || dnf install -y epel-release) || true
          (command -v yum && yum install -y sshpass || dnf install -y sshpass)
        else
          echo "Please install sshpass manually" >&2; exit 1

  tasks:
    # ---------- Export on router (run via localhost ssh) ----------
    - name: Export config (.rsc) on router
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/export file={{ inventory_hostname }}_config_{{ backup_ts }}"
      changed_when: true

    - name: Export config (.rsc) on router (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/export file={{ inventory_hostname }}_config_{{ backup_ts }}"
      changed_when: true

    - name: Export scripts (.rsc) on router
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/system script export file={{ inventory_hostname }}_scripts_{{ backup_ts }}"
      changed_when: true

    - name: Export scripts (.rsc) on router (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/system script export file={{ inventory_hostname }}_scripts_{{ backup_ts }}"
      changed_when: true

    - name: Export scheduler (.rsc) on router
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/system scheduler export file={{ inventory_hostname }}_scheduler_{{ backup_ts }}"
      changed_when: true

    - name: Export scheduler (.rsc) on router (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/system scheduler export file={{ inventory_hostname }}_scheduler_{{ backup_ts }}"
      changed_when: true

    - name: Create full binary backup (.backup) on router
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/system/backup/save name={{ inventory_hostname }}_full_{{ backup_ts }} dont-encrypt=yes"
      changed_when: true

    - name: Create full binary backup (.backup) on router (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/system/backup/save name={{ inventory_hostname }}_full_{{ backup_ts }} dont-encrypt=yes"
      changed_when: true

    # ---------- Copy back (scp) ----------
    - name: Copy config export to controller
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_config_{{ backup_ts }}.rsc
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy config export to controller (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_config_{{ backup_ts }}.rsc
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy scripts export to controller
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_scripts_{{ backup_ts }}.rsc
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy scripts export to controller (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_scripts_{{ backup_ts }}.rsc
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy scheduler export to controller
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_scheduler_{{ backup_ts }}.rsc
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy scheduler export to controller (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_scheduler_{{ backup_ts }}.rsc
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy full binary backup to controller
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_full_{{ backup_ts }}.backup
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    - name: Copy full binary backup to controller (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        scp -P {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}:/{{ inventory_hostname }}_full_{{ backup_ts }}.backup
        "{{ backup_base_dir }}/{{ inventory_hostname }}/"

    # ---------- Cleanup on router (exact filenames; non-fatal) ----------
    - name: Cleanup temp files on router (no password)
      delegate_to: localhost
      when: ansible_ssh_pass is not defined
      ansible.builtin.shell: >
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/file remove {{ inventory_hostname }}_config_{{ backup_ts }}.rsc;
         /file remove {{ inventory_hostname }}_scripts_{{ backup_ts }}.rsc;
         /file remove {{ inventory_hostname }}_scheduler_{{ backup_ts }}.rsc;
         /file remove {{ inventory_hostname }}_full_{{ backup_ts }}.backup" || true
      changed_when: true

    - name: Cleanup temp files on router (password auth)
      delegate_to: localhost
      when: ansible_ssh_pass is defined
      ansible.builtin.shell: >
        sshpass -p '{{ ansible_ssh_pass }}'
        ssh -p {{ ansible_port }} {{ ssh_args_common }}
        {{ ansible_user }}@{{ inventory_hostname }}
        "/file remove {{ inventory_hostname }}_config_{{ backup_ts }}.rsc;
         /file remove {{ inventory_hostname }}_scripts_{{ backup_ts }}.rsc;
         /file remove {{ inventory_hostname }}_scheduler_{{ backup_ts }}.rsc;
         /file remove {{ inventory_hostname }}_full_{{ backup_ts }}.backup" || true
      changed_when: true

    # ---------- Retention (local) ----------
    - name: Retain only last N files (local)
      delegate_to: localhost
      changed_when: false
      vars:
        keep: "{{ retention_keep }}"
        base: "{{ backup_base_dir }}/{{ inventory_hostname }}"
      ansible.builtin.shell: |
        for t in config scripts scheduler; do
          ls -1t "{{ base }}/{{ inventory_hostname }}_${t}_*.rsc" 2>/dev/null | awk 'NR>{{ keep }}' | xargs -r rm -f
        done
        ls -1t "{{ base }}/{{ inventory_hostname }}_full_*.backup" 2>/dev/null | awk 'NR>{{ keep }}' | xargs -r rm -f
